# Runs upgrade suite of integration tests
# Requires as input IMG ENV variable for make target
# Don't forget to use actions/checkout@v3 and actions/setup-go@v4 before

name: 'Upgrade integration test'
description: 'Runs upgrade suite of integration tests'
inputs:
  img-url:
    description: 'Env variable required for make target'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "test-cluster-1"
        args: >-
          --agents 0
          --k3s-arg "--disable=traefik@server:0"
    - name: Run upgrade integration test
      run: |
        kubectl config use-context k3d-test-cluster-1
        EXPORT_RESULT=true IMG=${{ inputs.img-url }} TARGET_BRANCH=${{github.base_ref}} make istio-upgrade-integration-test
      shell: bash