name: 'Upgrade integration test'
description: 'Runs upgrade suite of integration tests'
inputs:
  operator-image-name:
    description: 'Operator image used for test'
    required: true
  target_branch:
    description: 'Target branch'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Create Single Cluster
      uses: ./.github/actions/provision-k3d-cluster
      with:
        version: "1.29.7"
    - name: Run upgrade integration test
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          k3d image import ${{ inputs.operator-image-name }} -c k3s-default
        fi
        
        kubectl config use-context k3d-k3s-default
        EXPORT_RESULT=true IMG=${{ inputs.operator-image-name }} TARGET_BRANCH=${{inputs.target_branch}} make istio-upgrade-integration-test
      shell: bash
