version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "go"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
    ignore:
      - dependency-name: "sigs.k8s.io/controller-runtime"
        # We want to ignore istio dependencies, since the upgrade process is always a manual process, and we never used the dependabot PRs.
      - dependency-name: "istio.io/client-go"
      - dependency-name: "istio.io/api"
      - dependency-name: "istio.io/istio"
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io/*"
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "docker"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
  - package-ecosystem: "gomod"
    target-branch: "release-1.4"
    directory: "/"
    labels:
      - "go"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
    ignore:
      - dependency-name: "sigs.k8s.io/controller-runtime"
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      # We want to ignore istio dependencies, since the upgrade process is always a manual process, and we never used the dependabot PRs.
      - dependency-name: "istio.io/client-go"
      - dependency-name: "istio.io/api"
      - dependency-name: "istio.io/istio"
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io/*"
  - package-ecosystem: "docker"
    target-branch: "release-1.4"
    directory: "/"
    labels:
      - "docker"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
