apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: default-operator
  namespace: istio-system
  labels:
    kyma-project.io/module: istio
spec:
  hub: europe-docker.pkg.dev/kyma-project/prod/external/istio
  tag: "1.24.1-distroless"
  components:
    base:
      enabled: true
    cni:
      enabled: true
      namespace: istio-system
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-cni-node
                topologyKey: kubernetes.io/hostname
              weight: 100
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
    egressGateways:
    - enabled: false
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istio-egressgateway
                  topologyKey: kubernetes.io/hostname
                weight: 100
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istio-egressgateway
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 120Mi
        hpaSpec:
          maxReplicas: 10
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-egressgateway
          metrics:
            - resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 80
              type: Resource
          minReplicas: 3
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - istio-ingressgateway
                topologyKey: topology.kubernetes.io/zone
              weight: 100
        hpaSpec:
          maxReplicas: 10
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
          metrics:
          - resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 80
            type: Resource
          minReplicas: 3
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 0
      name: istio-ingressgateway
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istiod
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - istiod
                topologyKey: topology.kubernetes.io/zone
              weight: 100
        env:
        - name: PILOT_HTTP10
          value: "1"
        - name: METRIC_ROTATION_INTERVAL
          value: "5m0s"
        - name: METRIC_GRACEFUL_DELETION_INTERVAL
          value: "5m0s"
        hpaSpec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
          maxReplicas: 5
          minReplicas: 2
        podAnnotations:
          istios.operator.kyma-project.io/managed-by-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
        resources:
          limits:
            cpu: 4000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        serviceAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "15014"
          istios.operator.kyma-project.io/managed-by-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        BOOTSTRAP_XDS_AGENT: "true"
        CITADEL_SELF_SIGNED_CA_RSA_KEY_SIZE: "4096"
        WORKLOAD_RSA_KEY_SIZE: "3072"
      tracingServiceName: CANONICAL_NAME_ONLY
    defaultProviders:
      tracing: []
      metrics:
      - prometheus
    enablePrometheusMerge: false
    enableTracing: false
    extensionProviders:
    - name: kyma-traces
      opentelemetry:
          service: "telemetry-otlp-traces.kyma-system.svc.cluster.local"
          port: 4317
    - envoyFileAccessLog:
        logFormat:
          labels: {}
        path: /dev/stdout
      name: envoy
    - envoyFileAccessLog:
        logFormat:
          labels:
            start_time: "%START_TIME%"
            method: "%REQ(:METHOD)%"
            path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            protocol: "%PROTOCOL%"
            response_code: "%RESPONSE_CODE%"
            response_flags: "%RESPONSE_FLAGS%"
            response_code_details: "%RESPONSE_CODE_DETAILS%"
            connection_termination_details: "%CONNECTION_TERMINATION_DETAILS%"
            upstream_transport_failure_reason: "%CONNECTION_TERMINATION_DETAILS%"
            bytes_received: "%BYTES_RECEIVED%"
            bytes_sent: "%BYTES_SENT%"
            duration: "%DURATION%"
            upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
            x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
            user_agent: "%REQ(USER-AGENT)%"
            request_id: "%REQ(X-REQUEST-ID)%"
            authority: "%REQ(:AUTHORITY)%"
            upstream_host: "%UPSTREAM_HOST%"
            upstream_cluster: "%UPSTREAM_CLUSTER%"
            upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
            downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
            downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
            requested_server_name: "%REQUESTED_SERVER_NAME%"
            route_name: "%ROUTE_NAME%"
            traceparent: "%REQ(TRACEPARENT)%"
            tracestate: "%REQ(TRACESTATE)%"
        path: /dev/stdout
      name: stdout-json
    trustDomain: cluster.local
  profile: default
  values:
    base:
      enableCRDTemplates: false
      validationURL: ""
    cni:
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
    defaultRevision: ""
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-egressgateway
        secretVolumes:
        - mountPath: /etc/istio/egressgateway-certs
          name: egressgateway-certs
          secretName: istio-egressgateway-certs
        - mountPath: /etc/istio/egressgateway-ca-certs
          name: egressgateway-ca-certs
          secretName: istio-egressgateway-ca-certs
        type: ClusterIP
      istio-ingressgateway:
        autoscaleEnabled: true
        env: {}
        name: istio-ingressgateway
        podAnnotations:
          istios.operator.kyma-project.io/managed-by-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
          istios.operator.kyma-project.io/managed-by-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
        type: LoadBalancer
    global:
      configValidation: true
      defaultNodeSelector: {}
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      imagePullPolicy: IfNotPresent
      imagePullSecrets: []
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      jwtPolicy: third-party-jwt
      logAsJson: false
      logging:
        level: all:warn
      meshNetworks: {}
      mountMtlsCerts: false
      multiCluster:
        clusterName: ""
        enabled: false
      network: ""
      omitSidecarInjectorConfigMap: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: istio-kyma-priority
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ""
        excludeInboundPorts: ""
        excludeOutboundPorts: ""
        image: proxyv2
        includeIPRanges: '*'
        logLevel: warning
        privileged: false
        readinessInitialDelaySeconds: 5
        readinessPeriodSeconds: 15
        readinessFailureThreshold: 14
        startupProbe:
          enabled: true
          failureThreshold: 600
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 192Mi
        statusPort: 15020
        tracer: none
      proxy_init:
        image: proxyv2
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tracer:
        datadog: {}
        lightstep: {}
        stackdriver: {}
        zipkin: {}
    istiodRemote:
      injectionURL: ""
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      deploymentLabels: null
      env:
        CITADEL_SELF_SIGNED_CA_RSA_KEY_SIZE: "4096"
      image: pilot
      keepaliveMaxServerConnectionAge: 30m
      nodeSelector: {}
      podLabels: {}
      replicaCount: 1
      traceSampling: 1
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
      rewriteAppHTTPProbe: true
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: true
        stackdriver:
          enabled: false
