name: kyma-project.io/module/istio
team: kyma/Goat
images:
  - europe-docker.pkg.dev/kyma-project/prod/istio/main/istio-manager:main
  - europe-docker.pkg.dev/kyma-project/prod/external/istio/install-cni:1.30.2-distroless
  - europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.30.2-distroless
  - europe-docker.pkg.dev/kyma-project/prod/external/istio/pilot:1.30.2-distroless
  - europe-docker.pkg.dev/kyma-project/restricted-prod/external/istio/istio-install-cni-fips:1.30.2-1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/external/istio/istio-proxy-fips:1.30.2-1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/external/istio/istio-pilot-fips:1.30.2-1
