module-name: istio
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/istio/main/istio-manager:7d73e8ed487dfd9417c4ced96cb54f59adc95397
  - europe-docker.pkg.dev/kyma-project/prod/external/istio/install-cni:1.28.5-distroless
  - europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.28.5-distroless
  - europe-docker.pkg.dev/kyma-project/prod/external/istio/pilot:1.28.5-distroless
  - europe-docker.pkg.dev/kyma-project/restricted-prod/external/istio/istio-install-cni-fips:1.28.5-1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/external/istio/istio-proxy-fips:1.28.5-1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/external/istio/istio-pilot-fips:1.28.5-1
mend:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/tests/**"
    - "**/test/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/tests/**"
    - "**/test/**"
    - "**/*_test.go"
