resources:
- manager.yaml
- metrics_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: europe-docker.pkg.dev/kyma-project/prod/istio/releases/istio-manager
  newTag: to-be-replaced-by-make
patches:
- path: env-images.yaml
