apiVersion: v1
kind: Service
metadata:
  name: operator-metrics
  namespace: system
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: istio-operator.kyma-project.io
    control-plane: controller-manager
