apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: operator-vpa
  namespace: system
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: manager
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: 10000m
          memory: 16Gi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-controller-manager
  updatePolicy:
    minReplicas: 1
    updateMode: InPlaceOrRecreate
