apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: istio-egressgateway-vpa
  namespace: istio-system
  labels:
    kyma-project.io/module: istio
    app.kubernetes.io/component: egressgateway
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/name: istio-egressgateway
    app.kubernetes.io/instance: istio-egressgateway-default
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: istio-proxy
        controlledResources:
          - memory
        controlledValues: RequestsAndLimits
        maxAllowed:
          memory: 16Gi
        minAllowed:
          memory: 128Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-egressgateway
  updatePolicy:
    minReplicas: 1
    updateMode: InPlaceOrRecreate
