apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: istiod-vpa
  namespace: istio-system
  labels:
    kyma-project.io/module: istio
    app.kubernetes.io/component: pilot
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istiod-default
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: discovery
        controlledResources:
          - memory
        controlledValues: RequestsAndLimits
        maxAllowed:
          memory: 16Gi
        minAllowed:
          memory: 512Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  updatePolicy:
    minReplicas: 1
    updateMode: InPlaceOrRecreate
