apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: kyma-referer
  namespace: istio-system
spec:
  configPatches:
    - applyTo: BOOTSTRAP
      patch:
        operation: MERGE
        value:
          layered_runtime:
            layers:
              - name: kyma_referer
                static_layer:
                  envoy.reloadable_features.http_allow_partial_urls_in_referer: false
