apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kyma-gateway
  namespace: kyma-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kyma-gateway-certs
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES128-GCM-SHA256
    hosts:
      - "*.{{.DomainName}}"
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true # automatic 301 redirect from http to https
    hosts:
      - "*.{{.DomainName}}"
