apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-healthz
  namespace: istio-system
spec:
  gateways:
  - kyma-system/kyma-gateway
  hosts:
  - healthz.{{.DomainName}}
  http:
  - match:
    - uri:
        exact: /healthz/ready
    route:
    - destination:
        host: istio-ingressgateway.istio-system.svc.cluster.local
        port:
          number: 15021