apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kyma-priority
value: 2100000
globalDefault: false
description: "Used for Istio components that are managed by Kyma Istio Manager and must run in the cluster."
