apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kyma-project.io/module: istio
    app.kubernetes.io/name: metrics-reader
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/part-of: istio
  name: metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
