# permissions for end users to view istio.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-istio-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    kyma-project.io/managed-by: kyma
    kyma-project.io/module: istio
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - istios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - istios/status
  verbs:
  - get
