
name: 'Istio integration test'
description: 'Runs Istio integration tests'
inputs:
  evaluation:
    description: 'Controls whether the test should run for Evaluation or Production'
    required: false
  operator-image-name:
    description: 'Operator image used for test'
    required: true
  agents:
    description: 'Number of k3d agents created'
    required: true
  servers-memory:
    description: 'Amount of memory allocated to k3d cluster'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "test-cluster-1"
        args: >-
          --agents ${{ inputs.agents }}
          --image docker.io/rancher/k3s:v1.28.2-k3s1
          --servers-memory ${{ inputs.servers-memory }}
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --k3s-arg "--disable=traefik@server:0"
    - name: Run integration tests
      shell: bash
      run: |
        kubectl config use-context k3d-test-cluster-1
        if "${{ inputs.evaluation }}" == "true"; then
          TEST_EVALUATION=TRUE EXPORT_RESULT=true IMG=${{ inputs.operator-image-name }} make istio-integration-test
        else
          EXPORT_RESULT=true IMG=${{ inputs.operator-image-name }} make istio-integration-test
        fi
