apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: istio-operator-vpa
  namespace: kyma-system
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: manager
        maxAllowed:
          cpu: 10000m
          memory: 16Gi
        minAllowed:
          cpu: 10m
          memory: 64Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-controller-manager
  updatePolicy:
    minReplicas: 1
    updateMode: InPlaceOrRecreate
