apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    {{- include "load-testing.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-grafana
spec:
  gateways:
  - kyma-system/kyma-gateway
  hosts:
  - grafana.{{ .Values.Domain }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      allowOrigins:
      - regex: .*
    headers:
      request:
        set:
          x-forwarded-host: grafana.{{ .Values.Domain }}
    match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: {{ .Release.Name }}-grafana.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
      weight: 100