name: Main cache

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'go.mod'

jobs:

  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - name: build
        run: make build

  warm-image-cache:
    name: Warm image cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-manager-image
        with:
          operator-image-name: "istio-manager:main-cache"
          operator-version: "main"
