# This workflow is resposible for all kinds of integration tests that are run AFTER MERGE TO MAIN
# Those tests depend on a container image so in the first job we wait for the image build to succeed

name: Post submit integration tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "tests/performance/**"
      - "OWNERS"
      - "CODEOWNERS"
      - "sec-scanners-config.yaml"
      - ".github/**" #Ignoring since build job isn't triggered on the workflow directory changes
    branches:
      - main

permissions:
  contents: read

jobs:
  wait-for-image-build:
    name: Wait for image build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/wait-for-job-succeed-or-fail
        with:
          job-name: 'post-istio-operator-build'
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}

  istio-upgrade-integration-test:
    name: Istio upgrade integration test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: [wait-for-image-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: ./.github/actions/upgrade-integration-test

  slack_failed_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [istio-upgrade-integration-test]
    steps:
      - uses: actions/checkout@v3
      - name: Notify
        uses: ./.github/actions/slack-notification-failed-workflow
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
