name: Schedule Credentials Check

permissions:
  contents: read

on:
  schedule:
    - cron: '0 6 * * *' # Run every day at 06:00 AM

jobs:
  check-gardener-token:
    name: Check Gardener token
    environment:
      name: e2e
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check Gardener token
        env:
          GARDENER_TOKEN: ${{ secrets.GARDENER_TOKEN }}
          GARDENER_PROJECT_NAME: ${{ vars.GARDENER_PROJECT_NAME }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-gardener-token.sh"

  check-fips-registry:
    name: Check FIPS registry credentials
    environment:
      name: e2e
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check FIPS registry credentials
        env:
          FIPS_REGISTRY_SA: ${{ secrets.FIPS_REGISTRY_SA }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-fips-registry.sh"

  check-project-access-classic:
    name: Check GitHub project access
    environment:
      name: projects
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check GitHub project access
        env:
          GH_TOKEN: ${{ secrets.PROJECT_ACCESS_CLASSIC }}
          ORGANIZATION: kyma-project
          PROJECT_NUMBER: ${{ vars.PROJECT_ID }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-project-access.sh"

  check-slack-webhooks:
    name: Check Slack webhooks
    environment:
      name: notifications
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check Slack webhooks
        env:
          SLACK_RELEASE_WEBHOOK: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-slack-webhooks.sh"
