name: 'Kubernetes version compatibility check'
description: 'Runs Kubernetes version compatibility check'
inputs:
  operator-image-name:
    description: 'Operator image used for test'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "test-cluster-1"
        args: >-
          --agents 2
          --image docker.io/rancher/k3s:v1.29.4-k3s1
          --servers-memory=16g
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --k3s-arg "--disable=traefik@server:0"
    - name: Run integration tests
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          k3d image import ${{ inputs.operator-image-name }} -c test-cluster-1
        fi

        kubectl config use-context k3d-test-cluster-1
        EXPORT_RESULT=true IMG=${{ inputs.operator-image-name }} make istio-integration-test
      shell: bash
    - name: Check deprecations
      run: |
        set -eou pipefail
        GO111MODULE=on go install github.com/prometheus/prom2json/cmd/prom2json@v1.3.3
        kubectl get --context k3d-test-cluster-1 --raw /metrics | prom2json | jq '.[] | select(.name=="apiserver_requested_deprecated_apis").metrics[].labels' > deprecations.txt
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: html-reports
        path: tests/integration/reports/
    - uses: actions/upload-artifact@v4
      with:
        name: deprecation-report
        path: deprecations.txt
    - name: Check that deprecations are empty
      run: if [[ $(wc -l deprecations.txt | awk '{print $1}' ) != '0' ]]; then exit 1; fi
      shell: bash
